with months as (
  SELECT DATE_FORMAT(CONCAT(YEAR(CURDATE()), '01', '01'), '%M') as Month,
    DAYOFMONTH(LAST_DAY(CONCAT(YEAR(CURDATE()), '01', '01'))) as Days
  UNION
  SELECT DATE_FORMAT(CONCAT(YEAR(CURDATE()), '02', '01'), '%M') as Month,
    DAYOFMONTH(LAST_DAY(CONCAT(YEAR(CURDATE()), '02', '01'))) as Days
  UNION
  SELECT DATE_FORMAT(CONCAT(YEAR(CURDATE()), '03', '01'), '%M') as Month,
    DAYOFMONTH(LAST_DAY(CONCAT(YEAR(CURDATE()), '03', '01'))) as Days
  UNION
  SELECT DATE_FORMAT(CONCAT(YEAR(CURDATE()), '04', '01'), '%M') as Month,
    DAYOFMONTH(LAST_DAY(CONCAT(YEAR(CURDATE()), '04', '01'))) as Days
  UNION
  SELECT DATE_FORMAT(CONCAT(YEAR(CURDATE()), '05', '01'), '%M') as Month,
    DAYOFMONTH(LAST_DAY(CONCAT(YEAR(CURDATE()), '05', '01'))) as Days
  UNION
  SELECT DATE_FORMAT(CONCAT(YEAR(CURDATE()), '06', '01'), '%M') as Month,
    DAYOFMONTH(LAST_DAY(CONCAT(YEAR(CURDATE()), '06', '01'))) as Days
  UNION
  SELECT DATE_FORMAT(CONCAT(YEAR(CURDATE()), '07', '01'), '%M') as Month,
    DAYOFMONTH(LAST_DAY(CONCAT(YEAR(CURDATE()), '07', '01'))) as Days
  UNION
  SELECT DATE_FORMAT(CONCAT(YEAR(CURDATE()), '08', '01'), '%M') as Month,
    DAYOFMONTH(LAST_DAY(CONCAT(YEAR(CURDATE()), '08', '01'))) as Days
  UNION
  SELECT DATE_FORMAT(CONCAT(YEAR(CURDATE()), '09', '01'), '%M') as Month,
    DAYOFMONTH(LAST_DAY(CONCAT(YEAR(CURDATE()), '09', '01'))) as Days
  UNION
  SELECT DATE_FORMAT(CONCAT(YEAR(CURDATE()), '10', '01'), '%M') as Month,
    DAYOFMONTH(LAST_DAY(CONCAT(YEAR(CURDATE()), '10', '01'))) as Days
  UNION
  SELECT DATE_FORMAT(CONCAT(YEAR(CURDATE()), '11', '01'), '%M') as Month,
    DAYOFMONTH(LAST_DAY(CONCAT(YEAR(CURDATE()), '11', '01'))) as Days
  UNION
  SELECT DATE_FORMAT(CONCAT(YEAR(CURDATE()), '12', '01'), '%M') as Month,
    DAYOFMONTH(LAST_DAY(CONCAT(YEAR(CURDATE()), '12', '01'))) as Days
)
SELECT Month,
  Days
from months;